// AUTO-GENERATED BY z88-personal-website-generator — DO NOT EDIT
// Regenerate via POST /v1/sites/generate

import type { StatItem, SocialLink, CosplayItem, VideoItem } from '../types';

export const SITE_CONFIG = {
  "handle": "ammarsaa",
  "name": "Syed Ammar Ahmed",
  "tagline": "Full‑Stack Developer Crafting Modern Web Experiences",
  "bio": "Syed Ammar Ahmed is a passionate Jr. Software Developer based in Karachi, Pakistan. Blending code with creativity, he specializes in full‑stack MERN applications, responsive front‑end design, and seamless WordPress solutions. With a track record of e‑commerce platforms, API services, and mobile apps, Ammar delivers clean, performant code that turns ideas into reality.",
  "niche": "developer",
  "sections": {
    "hero": true,
    "about": true,
    "portfolio": true,
    "videos": false,
    "contact": "newsletter"
  },
  "theme": {
    "primaryColor": "#06B6D4",
    "accentColor": "#3B82F6",
    "bgColor": "#0F172A",
    "style": "cyberpunk-dark"
  },
  "contact": {
    "email": "founder@z88.tech",
    "type": "newsletter"
  }
} as const satisfies {
  handle: string; name: string; tagline: string; bio: string; niche: string;
  sections: { hero: boolean; about: boolean; portfolio: boolean; videos: boolean; contact: 'collab' | 'newsletter' | 'both' | 'none' };
  theme: { primaryColor: string; accentColor: string; bgColor: string; style: string };
  contact: { email: string; type: 'collab' | 'newsletter' | 'both' | 'none' };
};

export const STATS_DATA: StatItem[] = [
  {
    "label": "Years of Coding",
    "value": "2+"
  },
  {
    "label": "Projects Completed",
    "value": "6"
  },
  {
    "label": "Tech Stack",
    "value": "MERN, React, Node, Firebase"
  },
  {
    "label": "Location",
    "value": "Karachi, Pakistan"
  }
];

export const SOCIAL_LINKS: SocialLink[] = [];

export const PORTFOLIO_ITEMS: CosplayItem[] = [
  {
    "id": "p1",
    "title": "Xolen",
    "category": "E‑Commerce",
    "imageUrl": "/images/placeholder.jpg",
    "description": "A full‑stack MERN online store with real‑time inventory, payment integration, and admin dashboard.",
    "tags": [
      "MERN",
      "Node",
      "React",
      "MongoDB",
      "Stripe"
    ]
  },
  {
    "id": "p2",
    "title": "ShopSmart Online",
    "category": "E‑Commerce",
    "imageUrl": "/images/placeholder.jpg",
    "description": "Scalable MERN marketplace featuring product listings, user authentication, and order management.",
    "tags": [
      "React",
      "Express",
      "MongoDB",
      "Tailwind"
    ]
  },
  {
    "id": "p3",
    "title": "ShopSmart‑API",
    "category": "API Development",
    "imageUrl": "/images/placeholder.jpg",
    "description": "RESTful API powering the ShopSmart platform, built with Node.js, Express, and JWT security.",
    "tags": [
      "Node",
      "Express",
      "JWT",
      "Docker"
    ]
  },
  {
    "id": "p4",
    "title": "KaamKaro",
    "category": "Productivity Web App",
    "imageUrl": "/images/placeholder.jpg",
    "description": "React‑based todo application with CRUD operations, state management, and responsive UI.",
    "tags": [
      "React",
      "Hooks",
      "CSS",
      "LocalStorage"
    ]
  },
  {
    "id": "p5",
    "title": "Online Library Management System",
    "category": "Web Application",
    "imageUrl": "/images/placeholder.jpg",
    "description": "PHP‑driven library system for managing books, members, and lending records.",
    "tags": [
      "PHP",
      "MySQL",
      "Bootstrap"
    ]
  },
  {
    "id": "p6",
    "title": "Masooma Library Online",
    "category": "WordPress Site",
    "imageUrl": "/images/placeholder.jpg",
    "description": "Custom WordPress site delivering a digital reading library with user accounts and media streaming.",
    "tags": [
      "WordPress",
      "PHP",
      "Elementor"
    ]
  }
];

export const VIDEOS_DATA: VideoItem[] = [];

export const CATEGORIES: string[] = [
  'All',
  ...Array.from(new Set(PORTFOLIO_ITEMS.map((i) => i.category))),
];
